### PR TITLE
Add handling for async functions

### PR DESCRIPTION
**Pull request by rominf**

### CODE REVIEW

**Comment by sondrelg** [comment]
Thanks for opening this @rominf 👏

Would you mind adding a test to cover async function, so we don't accidentally break things in the future? 

As soon as tests are in place I'm happy to merge the PR 👍

**Comment by rominf** [comment]
@sondrelg Sure, I forgot about testing...

Should it be a unit or integration test?

**Comment by sondrelg** [comment]
A unit test with an async function being called is plenty 👏

**Comment by rominf** [comment]
Done. I hope this is what you wanted :-)

**Pull request merged**
